name: cmake

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  BUILD_TYPE: RELEASE
  TARGET_ARCH: linux64
  SYSTEMC_HOME: ${{github.workspace}}/systemc
  VCML_HOME: ${{github.workspace}}/vcml
  OR1KISS_HOME: ${{github.workspace}}/or1kiss

jobs:
  cmake:
    name: cmake
    runs-on: ubuntu-24.04

    steps:
    - name: Setup dependencies
      run: |
          sudo apt-get update -y -qq
          sudo apt-get install libelf-dev ninja-build libvncserver-dev libslirp-dev

    - name: Checkout or1kmvp
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Checkout or1kiss
      uses: actions/checkout@v3
      with:
        path: or1kiss
        repository: janweinstock/or1kiss
        submodules: 'recursive'

    - name: Checkout SystemC
      uses: actions/checkout@v3
      with:
        path: systemc
        repository: machineware-gmbh/systemc
        submodules: 'recursive'

    - name: Checkout VCML
      uses: actions/checkout@v3
      with:
        path: vcml
        repository: janweinstock/vcml
        submodules: 'recursive'

    - name: Configure
      run: cmake -B BUILD -G Ninja -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} .

    - name: Build
      run: cmake --build BUILD --config ${{env.BUILD_TYPE}} -j $(nproc)

    - name: Test
      working-directory: ${{github.workspace}}/BUILD
      run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure

