name: style

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  style:
    name: style
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Check Format
      run: ./utils/format -n

